[package]
name = "ehr_icp_project_backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ic-cdk = "0.12.0"
ic-cdk-macros = "0.13.1"
candid = "0.10.3"
serde = { version = "1.0", features = ["derive"] }
